// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
)

const adoptSeriesByNaturalKey = `-- name: AdoptSeriesByNaturalKey :one
UPDATE series
SET original_title = $1,
    tmdb_id        = $2,
    updated_at     = now()
WHERE type = $3
  AND title = $4
  AND year IS NOT DISTINCT FROM $5::int
  AND tmdb_id IS NULL
RETURNING id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
`

type AdoptSeriesByNaturalKeyParams struct {
	OriginalTitle *string `json:"originalTitle"`
	TmdbID        *int64  `json:"tmdbId"`
	Type          string  `json:"type"`
	Title         string  `json:"title"`
	Year          *int32  `json:"year"`
}

// 按自然键 (type, title, year) 在没有 TMDB ID 的剧里找一部，覆盖原名并补上 TMDB ID（目录源没给时仍为空）。
// 年份都为空也算同一部剧。没有这部剧时没有行。
func (q *Queries) AdoptSeriesByNaturalKey(ctx context.Context, arg AdoptSeriesByNaturalKeyParams) (Series, error) {
	row := q.db.QueryRow(ctx, adoptSeriesByNaturalKey,
		arg.OriginalTitle,
		arg.TmdbID,
		arg.Type,
		arg.Title,
		arg.Year,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :execrows
DELETE FROM episodes
WHERE id = $1
`

// 删除一集，绑定和弹幕随外键级联删除。
func (q *Queries) DeleteEpisode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEpisode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSeason = `-- name: DeleteSeason :execrows
DELETE FROM seasons
WHERE id = $1
`

// 删除一季，集、绑定和弹幕随外键级联删除。
func (q *Queries) DeleteSeason(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeason, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSeries = `-- name: DeleteSeries :one
DELETE FROM series
WHERE id = $1
RETURNING poster_image_id
`

// 删除一部剧，季、集、绑定和弹幕随外键级联删除。带回它的海报 ID，由调用方在同一个事务里删掉这张图（先删剧、再删图）。
// 用 RETURNING 取，不先 SELECT：同步正在写这部剧时，删除等它的事务提交，再按最新的一行删除，取到的是同步刚换上的海报。
// 剧不存在时没有行。
func (q *Queries) DeleteSeries(ctx context.Context, id int64) (*int64, error) {
	row := q.db.QueryRow(ctx, deleteSeries, id)
	var poster_image_id *int64
	err := row.Scan(&poster_image_id)
	return poster_image_id, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
FROM series
WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const insertSeries = `-- name: InsertSeries :one
INSERT INTO series (type, title, original_title, year, tmdb_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
`

type InsertSeriesParams struct {
	Type          string  `json:"type"`
	Title         string  `json:"title"`
	OriginalTitle *string `json:"originalTitle"`
	Year          *int32  `json:"year"`
	TmdbID        *int64  `json:"tmdbId"`
}

func (q *Queries) InsertSeries(ctx context.Context, arg InsertSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, insertSeries,
		arg.Type,
		arg.Title,
		arg.OriginalTitle,
		arg.Year,
		arg.TmdbID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const listEpisodesBySeries = `-- name: ListEpisodesBySeries :many
SELECT e.id, e.season_id, e.number, e.title, e.duration, e.created_at, e.updated_at
FROM episodes e
JOIN seasons se ON se.id = e.season_id
WHERE se.series_id = $1
ORDER BY e.number
`

// 一部剧的全部集，按集号排序。
func (q *Queries) ListEpisodesBySeries(ctx context.Context, seriesID int64) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Number,
			&i.Title,
			&i.Duration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonsBySeries = `-- name: ListSeasonsBySeries :many
SELECT id, number, title
FROM seasons
WHERE series_id = $1
ORDER BY number
`

type ListSeasonsBySeriesRow struct {
	ID     int64   `json:"id"`
	Number int32   `json:"number"`
	Title  *string `json:"title"`
}

// 剧详情、同步重算搜索列用：只选这几列，不取搜索列本身。
func (q *Queries) ListSeasonsBySeries(ctx context.Context, seriesID int64) ([]ListSeasonsBySeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeasonsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonsBySeriesRow{}
	for rows.Next() {
		var i ListSeasonsBySeriesRow
		if err := rows.Scan(&i.ID, &i.Number, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeries = `-- name: ListSeries :many
SELECT s.id, s.type, s.title, s.original_title, s.year, s.poster_image_id,
       count(DISTINCT se.id)::int                         AS season_count,
       count(DISTINCT e.id)::int                          AS episode_count,
       count(DISTINCT b.episode_id)::int                  AS bound_episode_count,
       count(b.id)::int                                   AS binding_count,
       count(b.id) FILTER (WHERE b.status = 'dead')::int AS dead_binding_count,
       EXISTS (SELECT 1
               FROM season_bindings sb
               JOIN seasons fse ON fse.id = sb.season_id
               WHERE fse.series_id = s.id
                 AND sb.follow)                           AS following
FROM series s
LEFT JOIN seasons se ON se.series_id = s.id
LEFT JOIN episodes e ON e.season_id = se.id
LEFT JOIN bindings b ON b.episode_id = e.id
GROUP BY s.id
ORDER BY s.id
`

type ListSeriesRow struct {
	ID                int64   `json:"id"`
	Type              string  `json:"type"`
	Title             string  `json:"title"`
	OriginalTitle     *string `json:"originalTitle"`
	Year              *int32  `json:"year"`
	PosterImageID     *int64  `json:"posterImageId"`
	SeasonCount       int32   `json:"seasonCount"`
	EpisodeCount      int32   `json:"episodeCount"`
	BoundEpisodeCount int32   `json:"boundEpisodeCount"`
	BindingCount      int32   `json:"bindingCount"`
	DeadBindingCount  int32   `json:"deadBindingCount"`
	Following         bool    `json:"following"`
}

// 剧列表：全部剧连同季数、集数和绑定统计，一条 SQL 聚合。没有季、集、绑定的计为 0。
// 一集有多个绑定时连接出多行，所以季数、集数、已绑定集数都按 DISTINCT 计。following 表示有开着追更的季绑定。
func (q *Queries) ListSeries(ctx context.Context) ([]ListSeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesRow{}
	for rows.Next() {
		var i ListSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.OriginalTitle,
			&i.Year,
			&i.PosterImageID,
			&i.SeasonCount,
			&i.EpisodeCount,
			&i.BoundEpisodeCount,
			&i.BindingCount,
			&i.DeadBindingCount,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeriesPoster = `-- name: SetSeriesPoster :exec
UPDATE series
SET poster_image_id = $2
WHERE id = $1
`

type SetSeriesPosterParams struct {
	ID            int64  `json:"id"`
	PosterImageID *int64 `json:"posterImageId"`
}

// 剧指向新的海报，没有图时为 null。
func (q *Queries) SetSeriesPoster(ctx context.Context, arg SetSeriesPosterParams) error {
	_, err := q.db.Exec(ctx, setSeriesPoster, arg.ID, arg.PosterImageID)
	return err
}

const updateSeriesByTMDBID = `-- name: UpdateSeriesByTMDBID :one
UPDATE series
SET title          = $1,
    original_title = $2,
    year           = $3,
    updated_at     = now()
WHERE type = $4
  AND tmdb_id = $5::bigint
RETURNING id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
`

type UpdateSeriesByTMDBIDParams struct {
	Title         string  `json:"title"`
	OriginalTitle *string `json:"originalTitle"`
	Year          *int32  `json:"year"`
	Type          string  `json:"type"`
	TmdbID        int64   `json:"tmdbId"`
}

// 按身份 (type, tmdb_id) 更新一部剧：标题、年份、原名都随目录源覆盖（见 docs/adr/0007）。没有这部剧时没有行。
// 海报由同步核心随后按 sha256 处理，带回整行是为了剧现在的海报。
func (q *Queries) UpdateSeriesByTMDBID(ctx context.Context, arg UpdateSeriesByTMDBIDParams) (Series, error) {
	row := q.db.QueryRow(ctx, updateSeriesByTMDBID,
		arg.Title,
		arg.OriginalTitle,
		arg.Year,
		arg.Type,
		arg.TmdbID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const upsertEpisode = `-- name: UpsertEpisode :one
INSERT INTO episodes (season_id, number, title, duration)
VALUES ($1, $2, $3, $4)
ON CONFLICT (season_id, number) DO UPDATE
SET title      = excluded.title,
    duration   = excluded.duration,
    updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertEpisodeParams struct {
	SeasonID int64   `json:"seasonId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
	Duration *int32  `json:"duration"`
}

type UpsertEpisodeRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (season_id, number) 写入一集，规则同 UpsertSeason。
func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (UpsertEpisodeRow, error) {
	row := q.db.QueryRow(ctx, upsertEpisode,
		arg.SeasonID,
		arg.Number,
		arg.Title,
		arg.Duration,
	)
	var i UpsertEpisodeRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertSeason = `-- name: UpsertSeason :one
INSERT INTO seasons (series_id, number, title)
VALUES ($1, $2, $3)
ON CONFLICT (series_id, number) DO UPDATE
SET title      = excluded.title,
    updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertSeasonParams struct {
	SeriesID int64   `json:"seriesId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
}

type UpsertSeasonRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (series_id, number) 写入一季：匹配上就用目录源的数据覆盖键以外的字段，匹配不上就新增。
// created 表示这一行是这次新增的：新插入的行 xmax 为 0，ON CONFLICT DO UPDATE 更新过的行不为 0。
func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (UpsertSeasonRow, error) {
	row := q.db.QueryRow(ctx, upsertSeason, arg.SeriesID, arg.Number, arg.Title)
	var i UpsertSeasonRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
