// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlc

import (
	"context"
)

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT content_type, data
FROM images
WHERE id = $1
`

type GetImageRow struct {
	ContentType string `json:"contentType"`
	Data        []byte `json:"data"`
}

// 图片接口用：原始字节与 content-type。
func (q *Queries) GetImage(ctx context.Context, id int64) (GetImageRow, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i GetImageRow
	err := row.Scan(&i.ContentType, &i.Data)
	return i, err
}

const getImageSHA256 = `-- name: GetImageSHA256 :one
SELECT sha256
FROM images
WHERE id = $1
`

// 同步时与目录源的新图比较，不取图片本身。
func (q *Queries) GetImageSHA256(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getImageSHA256, id)
	var sha256 []byte
	err := row.Scan(&sha256)
	return sha256, err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO images (content_type, data, sha256)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertImageParams struct {
	ContentType string `json:"contentType"`
	Data        []byte `json:"data"`
	Sha256      []byte `json:"sha256"`
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertImage, arg.ContentType, arg.Data, arg.Sha256)
	var id int64
	err := row.Scan(&id)
	return id, err
}
