// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"time"
)

type Episode struct {
	ID        int64     `json:"id"`
	SeasonID  int64     `json:"seasonId"`
	Number    int32     `json:"number"`
	Title     *string   `json:"title"`
	Duration  *int32    `json:"duration"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Series struct {
	ID            int64     `json:"id"`
	Type          string    `json:"type"`
	Title         string    `json:"title"`
	OriginalTitle *string   `json:"originalTitle"`
	Year          *int32    `json:"year"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	PosterImageID *int64    `json:"posterImageId"`
	TmdbID        *int64    `json:"tmdbId"`
}

type SyncRun struct {
	ID              int64      `json:"id"`
	Trigger         string     `json:"trigger"`
	Status          string     `json:"status"`
	StartedAt       time.Time  `json:"startedAt"`
	FinishedAt      *time.Time `json:"finishedAt"`
	Total           *int32     `json:"total"`
	Done            int32      `json:"done"`
	CreatedSeries   int32      `json:"createdSeries"`
	CreatedSeasons  int32      `json:"createdSeasons"`
	CreatedEpisodes int32      `json:"createdEpisodes"`
	Warnings        []string   `json:"warnings"`
	WarningCount    int32      `json:"warningCount"`
	Error           *string    `json:"error"`
}
