// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package catalogdb

import (
	"context"
	"time"
)

const adoptSeriesByNaturalKey = `-- name: AdoptSeriesByNaturalKey :one
UPDATE series
SET original_title = $1,
    tmdb_id        = $2,
    updated_at     = now()
WHERE type = $3
  AND title = $4
  AND year IS NOT DISTINCT FROM $5::int
  AND tmdb_id IS NULL
RETURNING id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
`

type AdoptSeriesByNaturalKeyParams struct {
	OriginalTitle *string `json:"originalTitle"`
	TmdbID        *int64  `json:"tmdbId"`
	Type          string  `json:"type"`
	Title         string  `json:"title"`
	Year          *int32  `json:"year"`
}

// 按自然键 (type, title, year) 在没有 TMDB ID 的剧里找一部，覆盖原名并补上 TMDB ID（目录源没给时仍为空）。
// 年份都为空也算同一部剧。没有这部剧时没有行。
func (q *Queries) AdoptSeriesByNaturalKey(ctx context.Context, arg AdoptSeriesByNaturalKeyParams) (Series, error) {
	row := q.db.QueryRow(ctx, adoptSeriesByNaturalKey,
		arg.OriginalTitle,
		arg.TmdbID,
		arg.Type,
		arg.Title,
		arg.Year,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (trigger, status, started_at)
VALUES ($1, 'running', $2)
RETURNING id
`

type CreateSyncRunParams struct {
	Trigger   string    `json:"trigger"`
	StartedAt time.Time `json:"startedAt"`
}

// 开始时间取自应用的时钟：定时同步按它算下一次的时间。
func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSyncRun, arg.Trigger, arg.StartedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEpisode = `-- name: DeleteEpisode :execrows
DELETE FROM episodes
WHERE id = $1
`

// 删除一集，绑定和弹幕随外键级联删除。
func (q *Queries) DeleteEpisode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEpisode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const deleteOldSyncRuns = `-- name: DeleteOldSyncRuns :exec
DELETE FROM sync_runs
WHERE id NOT IN (SELECT id FROM sync_runs ORDER BY id DESC LIMIT $1)
`

// 只保留最近 keep 次：新同步开始时先删到剩 19 次，再插入这一次。
func (q *Queries) DeleteOldSyncRuns(ctx context.Context, keep int32) error {
	_, err := q.db.Exec(ctx, deleteOldSyncRuns, keep)
	return err
}

const deleteSeason = `-- name: DeleteSeason :execrows
DELETE FROM seasons
WHERE id = $1
`

// 删除一季，集、绑定和弹幕随外键级联删除。
func (q *Queries) DeleteSeason(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeason, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSeries = `-- name: DeleteSeries :one
DELETE FROM series
WHERE id = $1
RETURNING poster_image_id
`

// 删除一部剧，季、集、绑定和弹幕随外键级联删除。带回它的海报 ID，由调用方在同一个事务里删掉这张图（先删剧、再删图）。
// 用 RETURNING 取，不先 SELECT：同步正在写这部剧时，删除等它的事务提交，再按最新的一行删除，取到的是同步刚换上的海报。
// 剧不存在时没有行。
func (q *Queries) DeleteSeries(ctx context.Context, id int64) (*int64, error) {
	row := q.db.QueryRow(ctx, deleteSeries, id)
	var poster_image_id *int64
	err := row.Scan(&poster_image_id)
	return poster_image_id, err
}

const getImage = `-- name: GetImage :one
SELECT content_type, data
FROM images
WHERE id = $1
`

type GetImageRow struct {
	ContentType string `json:"contentType"`
	Data        []byte `json:"data"`
}

// 图片接口用：原始字节与 content-type。
func (q *Queries) GetImage(ctx context.Context, id int64) (GetImageRow, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i GetImageRow
	err := row.Scan(&i.ContentType, &i.Data)
	return i, err
}

const getImageSHA256 = `-- name: GetImageSHA256 :one
SELECT sha256
FROM images
WHERE id = $1
`

// 同步时与目录源的新图比较，不取图片本身。
func (q *Queries) GetImageSHA256(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getImageSHA256, id)
	var sha256 []byte
	err := row.Scan(&sha256)
	return sha256, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
FROM series
WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const getSyncRun = `-- name: GetSyncRun :one
SELECT id, trigger, status, started_at, finished_at, total, done, created_series, created_seasons, created_episodes, warnings, warning_count, error
FROM sync_runs
WHERE id = $1
`

func (q *Queries) GetSyncRun(ctx context.Context, id int64) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getSyncRun, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Total,
		&i.Done,
		&i.CreatedSeries,
		&i.CreatedSeasons,
		&i.CreatedEpisodes,
		&i.Warnings,
		&i.WarningCount,
		&i.Error,
	)
	return i, err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO images (content_type, data, sha256)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertImageParams struct {
	ContentType string `json:"contentType"`
	Data        []byte `json:"data"`
	Sha256      []byte `json:"sha256"`
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertImage, arg.ContentType, arg.Data, arg.Sha256)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSeries = `-- name: InsertSeries :one
INSERT INTO series (type, title, original_title, year, tmdb_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
`

type InsertSeriesParams struct {
	Type          string  `json:"type"`
	Title         string  `json:"title"`
	OriginalTitle *string `json:"originalTitle"`
	Year          *int32  `json:"year"`
	TmdbID        *int64  `json:"tmdbId"`
}

func (q *Queries) InsertSeries(ctx context.Context, arg InsertSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, insertSeries,
		arg.Type,
		arg.Title,
		arg.OriginalTitle,
		arg.Year,
		arg.TmdbID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const interruptRunningSyncRuns = `-- name: InterruptRunningSyncRuns :execrows
UPDATE sync_runs
SET status = 'interrupted'
WHERE status = 'running'
`

// 把残留的 running（进程崩溃或被杀）改为 interrupted，结束时间未知，保持为空。
// 只能在持有同步的租约时调用：这时不会有正在进行的同步。
func (q *Queries) InterruptRunningSyncRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, interruptRunningSyncRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEpisodesBySeries = `-- name: ListEpisodesBySeries :many
SELECT e.id, e.season_id, e.number, e.title, e.duration, e.created_at, e.updated_at
FROM episodes e
JOIN seasons se ON se.id = e.season_id
WHERE se.series_id = $1
ORDER BY e.number
`

// 一部剧的全部集，按集号排序。
func (q *Queries) ListEpisodesBySeries(ctx context.Context, seriesID int64) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Number,
			&i.Title,
			&i.Duration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonsBySeries = `-- name: ListSeasonsBySeries :many
SELECT id, number, title
FROM seasons
WHERE series_id = $1
ORDER BY number
`

type ListSeasonsBySeriesRow struct {
	ID     int64   `json:"id"`
	Number int32   `json:"number"`
	Title  *string `json:"title"`
}

// 剧详情、同步重算搜索列用：只选这几列，不取搜索列本身。
func (q *Queries) ListSeasonsBySeries(ctx context.Context, seriesID int64) ([]ListSeasonsBySeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeasonsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonsBySeriesRow{}
	for rows.Next() {
		var i ListSeasonsBySeriesRow
		if err := rows.Scan(&i.ID, &i.Number, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeries = `-- name: ListSeries :many
SELECT s.id, s.type, s.title, s.original_title, s.year, s.tmdb_id, s.poster_image_id,
       count(DISTINCT se.id)::int                         AS season_count,
       count(DISTINCT e.id)::int                          AS episode_count,
       count(DISTINCT b.episode_id)::int                  AS bound_episode_count,
       count(b.id)::int                                   AS binding_count,
       count(b.id) FILTER (WHERE b.status = 'dead')::int AS dead_binding_count,
       EXISTS (SELECT 1
               FROM season_bindings sb
               JOIN seasons fse ON fse.id = sb.season_id
               WHERE fse.series_id = s.id
                 AND sb.follow)                           AS following
FROM series s
LEFT JOIN seasons se ON se.series_id = s.id
LEFT JOIN episodes e ON e.season_id = se.id
LEFT JOIN bindings b ON b.episode_id = e.id
GROUP BY s.id
ORDER BY s.id
`

type ListSeriesRow struct {
	ID                int64   `json:"id"`
	Type              string  `json:"type"`
	Title             string  `json:"title"`
	OriginalTitle     *string `json:"originalTitle"`
	Year              *int32  `json:"year"`
	TmdbID            *int64  `json:"tmdbId"`
	PosterImageID     *int64  `json:"posterImageId"`
	SeasonCount       int32   `json:"seasonCount"`
	EpisodeCount      int32   `json:"episodeCount"`
	BoundEpisodeCount int32   `json:"boundEpisodeCount"`
	BindingCount      int32   `json:"bindingCount"`
	DeadBindingCount  int32   `json:"deadBindingCount"`
	Following         bool    `json:"following"`
}

// 剧列表：全部剧连同季数、集数和绑定统计，一条 SQL 聚合。没有季、集、绑定的计为 0。
// 一集有多个绑定时连接出多行，所以季数、集数、已绑定集数都按 DISTINCT 计。following 表示有开着追更的季绑定。
// tmdb_id 用来在列表上标出没有 TMDB ID、按标题和年份对应的剧。
func (q *Queries) ListSeries(ctx context.Context) ([]ListSeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesRow{}
	for rows.Next() {
		var i ListSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.OriginalTitle,
			&i.Year,
			&i.TmdbID,
			&i.PosterImageID,
			&i.SeasonCount,
			&i.EpisodeCount,
			&i.BoundEpisodeCount,
			&i.BindingCount,
			&i.DeadBindingCount,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRuns = `-- name: ListSyncRuns :many
SELECT id, trigger, status, started_at, finished_at, total, done,
       created_series, created_seasons, created_episodes, warning_count, error
FROM sync_runs
ORDER BY id DESC
LIMIT $1
`

type ListSyncRunsRow struct {
	ID              int64      `json:"id"`
	Trigger         string     `json:"trigger"`
	Status          string     `json:"status"`
	StartedAt       time.Time  `json:"startedAt"`
	FinishedAt      *time.Time `json:"finishedAt"`
	Total           *int32     `json:"total"`
	Done            int32      `json:"done"`
	CreatedSeries   int32      `json:"createdSeries"`
	CreatedSeasons  int32      `json:"createdSeasons"`
	CreatedEpisodes int32      `json:"createdEpisodes"`
	WarningCount    int32      `json:"warningCount"`
	Error           *string    `json:"error"`
}

// 列表不带警告正文。
func (q *Queries) ListSyncRuns(ctx context.Context, limit int32) ([]ListSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, listSyncRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncRunsRow{}
	for rows.Next() {
		var i ListSyncRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Total,
			&i.Done,
			&i.CreatedSeries,
			&i.CreatedSeasons,
			&i.CreatedEpisodes,
			&i.WarningCount,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeasonSearchVectors = `-- name: SetSeasonSearchVectors :exec
UPDATE seasons se
SET search_vector = u.vector::tsvector
FROM (SELECT unnest($1::bigint[]) AS id, unnest($2::text[]) AS vector) u
WHERE se.id = u.id
  AND se.search_vector IS DISTINCT FROM u.vector::tsvector
`

type SetSeasonSearchVectorsParams struct {
	Ids     []int64  `json:"ids"`
	Vectors []string `json:"vectors"`
}

// 一条语句写入多季的搜索列，没变的不重写（列上有 GIN 索引，重写一行要重新插入它的全部词条）。
// 搜索列是 Go 生成的 tsvector 文本（catalog.SearchVector），直接转换，不经过 PostgreSQL 的分词器。
func (q *Queries) SetSeasonSearchVectors(ctx context.Context, arg SetSeasonSearchVectorsParams) error {
	_, err := q.db.Exec(ctx, setSeasonSearchVectors, arg.Ids, arg.Vectors)
	return err
}

const setSeriesPoster = `-- name: SetSeriesPoster :exec
UPDATE series
SET poster_image_id = $2
WHERE id = $1
`

type SetSeriesPosterParams struct {
	ID            int64  `json:"id"`
	PosterImageID *int64 `json:"posterImageId"`
}

// 剧指向新的海报，没有图时为 null。
func (q *Queries) SetSeriesPoster(ctx context.Context, arg SetSeriesPosterParams) error {
	_, err := q.db.Exec(ctx, setSeriesPoster, arg.ID, arg.PosterImageID)
	return err
}

const updateSeriesByTMDBID = `-- name: UpdateSeriesByTMDBID :one
UPDATE series
SET title          = $1,
    original_title = $2,
    year           = $3,
    updated_at     = now()
WHERE type = $4
  AND tmdb_id = $5::bigint
RETURNING id, type, title, original_title, year, created_at, updated_at, poster_image_id, tmdb_id
`

type UpdateSeriesByTMDBIDParams struct {
	Title         string  `json:"title"`
	OriginalTitle *string `json:"originalTitle"`
	Year          *int32  `json:"year"`
	Type          string  `json:"type"`
	TmdbID        int64   `json:"tmdbId"`
}

// 按身份 (type, tmdb_id) 更新一部剧：标题、年份、原名都随目录源覆盖（见 docs/adr/0007）。没有这部剧时没有行。
// 海报由同步核心随后按 sha256 处理，带回整行是为了剧现在的海报。
func (q *Queries) UpdateSeriesByTMDBID(ctx context.Context, arg UpdateSeriesByTMDBIDParams) (Series, error) {
	row := q.db.QueryRow(ctx, updateSeriesByTMDBID,
		arg.Title,
		arg.OriginalTitle,
		arg.Year,
		arg.Type,
		arg.TmdbID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
		&i.TmdbID,
	)
	return i, err
}

const updateSyncRun = `-- name: UpdateSyncRun :exec
UPDATE sync_runs
SET status           = $1,
    total            = $2,
    done             = $3,
    created_series   = $4,
    created_seasons  = $5,
    created_episodes = $6,
    warnings         = coalesce($7, warnings),
    warning_count    = $8,
    error            = $9,
    finished_at      = CASE WHEN $1 = 'running' THEN NULL ELSE now() END
WHERE id = $10
`

type UpdateSyncRunParams struct {
	Status          string   `json:"status"`
	Total           *int32   `json:"total"`
	Done            int32    `json:"done"`
	CreatedSeries   int32    `json:"createdSeries"`
	CreatedSeasons  int32    `json:"createdSeasons"`
	CreatedEpisodes int32    `json:"createdEpisodes"`
	Warnings        []string `json:"warnings"`
	WarningCount    int32    `json:"warningCount"`
	Error           *string  `json:"error"`
	ID              int64    `json:"id"`
}

// 写入一次同步的进度或最终状态；状态不再是 running 时记下结束时间。warnings 为 null 时不改（警告没有新增的进度）。
func (q *Queries) UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) error {
	_, err := q.db.Exec(ctx, updateSyncRun,
		arg.Status,
		arg.Total,
		arg.Done,
		arg.CreatedSeries,
		arg.CreatedSeasons,
		arg.CreatedEpisodes,
		arg.Warnings,
		arg.WarningCount,
		arg.Error,
		arg.ID,
	)
	return err
}

const upsertEpisodes = `-- name: UpsertEpisodes :one
WITH written AS (
    INSERT INTO episodes (season_id, number, title, duration)
    SELECT $1::bigint,
           unnest($2::int[]),
           nullif(unnest($3::text[]), ''),
           nullif(unnest($4::int[]), -1)
    ON CONFLICT (season_id, number) DO UPDATE
    SET title      = excluded.title,
        duration   = excluded.duration,
        updated_at = now()
    WHERE (episodes.title, episodes.duration) IS DISTINCT FROM (excluded.title, excluded.duration)
    RETURNING xmax = 0 AS created
)
SELECT count(*) FILTER (WHERE created)::int
FROM written
`

type UpsertEpisodesParams struct {
	SeasonID  int64    `json:"seasonId"`
	Numbers   []int32  `json:"numbers"`
	Titles    []string `json:"titles"`
	Durations []int32  `json:"durations"`
}

// 一条语句写入一季的集，按自然键 (season_id, number) 匹配：匹配上且标题或时长变了就覆盖，没变的不重写；匹配不上就新增。
// 返回新增的集数（新插入的行 xmax 为 0）。标题空串、时长 -1 存为 null。
// 同一批里集号不能重复（ON CONFLICT DO UPDATE 不能在一条语句里改同一行两次），调用方先去重。
func (q *Queries) UpsertEpisodes(ctx context.Context, arg UpsertEpisodesParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertEpisodes,
		arg.SeasonID,
		arg.Numbers,
		arg.Titles,
		arg.Durations,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertSeason = `-- name: UpsertSeason :one
INSERT INTO seasons (series_id, number, title)
VALUES ($1, $2, $3)
ON CONFLICT (series_id, number) DO UPDATE
SET title      = excluded.title,
    updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertSeasonParams struct {
	SeriesID int64   `json:"seriesId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
}

type UpsertSeasonRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (series_id, number) 写入一季：匹配上就用目录源的数据覆盖键以外的字段，匹配不上就新增。
// created 表示这一行是这次新增的：新插入的行 xmax 为 0，ON CONFLICT DO UPDATE 更新过的行不为 0。
func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (UpsertSeasonRow, error) {
	row := q.db.QueryRow(ctx, upsertSeason, arg.SeriesID, arg.Number, arg.Title)
	var i UpsertSeasonRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
