// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package blockworddb

import (
	"context"
	"time"
)

const createBlockedWord = `-- name: CreateBlockedWord :one
INSERT INTO blocked_words (kind, pattern, dedup_key)
VALUES ($1, $2, $3)
RETURNING id, kind, pattern, created_at
`

type CreateBlockedWordParams struct {
	Kind     string `json:"kind"`
	Pattern  string `json:"pattern"`
	DedupKey string `json:"dedupKey"`
}

type CreateBlockedWordRow struct {
	ID        int64     `json:"id"`
	Kind      string    `json:"kind"`
	Pattern   string    `json:"pattern"`
	CreatedAt time.Time `json:"createdAt"`
}

// 同类型、dedup_key 相同时违反唯一约束。
func (q *Queries) CreateBlockedWord(ctx context.Context, arg CreateBlockedWordParams) (CreateBlockedWordRow, error) {
	row := q.db.QueryRow(ctx, createBlockedWord, arg.Kind, arg.Pattern, arg.DedupKey)
	var i CreateBlockedWordRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Pattern,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlockedWord = `-- name: DeleteBlockedWord :execrows
DELETE FROM blocked_words
WHERE id = $1
`

func (q *Queries) DeleteBlockedWord(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockedWord, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBlockedWords = `-- name: ListBlockedWords :many
SELECT id, kind, pattern, created_at
FROM blocked_words
ORDER BY id DESC
`

type ListBlockedWordsRow struct {
	ID        int64     `json:"id"`
	Kind      string    `json:"kind"`
	Pattern   string    `json:"pattern"`
	CreatedAt time.Time `json:"createdAt"`
}

// 全部屏蔽词，新加的在前。
func (q *Queries) ListBlockedWords(ctx context.Context) ([]ListBlockedWordsRow, error) {
	rows, err := q.db.Query(ctx, listBlockedWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedWordsRow{}
	for rows.Next() {
		var i ListBlockedWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Pattern,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
