// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/kzw200015/danfuse/backend/internal/config"
	"github.com/kzw200015/danfuse/backend/internal/database"
	"github.com/kzw200015/danfuse/backend/internal/handler"
	"github.com/kzw200015/danfuse/backend/internal/pkg/logger"
	"github.com/kzw200015/danfuse/backend/internal/server"
)

// Injectors from wire.go:

// Init 组装整个应用：解析配置 → 初始化日志 → 连接数据库并自动迁移 → 构造各层组件。
// 修改依赖关系后执行 `make wire` 重新生成 wire_gen.go。
func Init(ctx context.Context, configPath string) (*App, func(), error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, nil, err
	}
	configServer := configConfig.Server
	log := configConfig.Log
	slogLogger := logger.New(log)
	configDatabase := configConfig.Database
	pool, cleanup, err := database.NewPool(ctx, configDatabase, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	healthHandler := handler.NewHealthHandler(pool)
	handlers := &handler.Handlers{
		Health: healthHandler,
	}
	serverServer := server.New(configServer, slogLogger, handlers)
	app := New(serverServer)
	return app, func() {
		cleanup()
	}, nil
}
