// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/kzw200015/danfuse/backend/internal/config"
	"github.com/kzw200015/danfuse/backend/internal/dandan"
	"github.com/kzw200015/danfuse/backend/internal/database"
	"github.com/kzw200015/danfuse/backend/internal/handler"
	"github.com/kzw200015/danfuse/backend/internal/pkg/logger"
	"github.com/kzw200015/danfuse/backend/internal/repository"
	"github.com/kzw200015/danfuse/backend/internal/server"
	"github.com/kzw200015/danfuse/backend/internal/service"
)

// Injectors from wire.go:

// Init 组装整个应用：解析配置 → 初始化日志 → 连接数据库并自动迁移 → 构造各层组件。
// 修改依赖关系后执行 `make wire` 重新生成 wire_gen.go。
func Init(ctx context.Context, configPath string) (*App, func(), error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, nil, err
	}
	configServer := configConfig.Server
	dandanplay := configConfig.Dandanplay
	log := configConfig.Log
	slogLogger := logger.New(log)
	configDatabase := configConfig.Database
	pool, cleanup, err := database.NewPool(ctx, configDatabase, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	healthHandler := handler.NewHealthHandler(pool)
	sqlStore := repository.NewStore(pool)
	bilibili := configConfig.Bilibili
	registry := newSourceRegistry(bilibili)
	catalogService := service.NewCatalogService(sqlStore, registry)
	catalogHandler := handler.NewCatalogHandler(catalogService)
	bindingService := service.NewBindingService(sqlStore, registry, slogLogger)
	bindingHandler := handler.NewBindingHandler(bindingService)
	catalogSource := configConfig.CatalogSource
	source := newCatalogSource(catalogSource)
	sync := configConfig.Sync
	syncService := service.NewSyncService(sqlStore, pool, source, sync, slogLogger)
	syncHandler := handler.NewSyncHandler(syncService)
	settingsHandler := handler.NewSettingsHandler(dandanplay, catalogSource, sync, bilibili)
	handlers := &handler.Handlers{
		Health:   healthHandler,
		Catalog:  catalogHandler,
		Binding:  bindingHandler,
		Sync:     syncHandler,
		Settings: settingsHandler,
	}
	localProvider := service.NewLocalProvider(sqlStore, registry)
	aggregator := newAggregator(localProvider)
	dandanHandler := dandan.NewHandler(aggregator)
	serverServer := server.New(configServer, dandanplay, slogLogger, handlers, dandanHandler)
	app := New(serverServer, syncService)
	return app, func() {
		cleanup()
	}, nil
}
