// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bindings.sql

package repository

import (
	"context"
)

const bindingExists = `-- name: BindingExists :one
SELECT EXISTS (SELECT 1 FROM bindings WHERE episode_id = $1 AND adapter = $2 AND ref = $3)
`

type BindingExistsParams struct {
	EpisodeID int64  `json:"episodeId"`
	Adapter   string `json:"adapter"`
	Ref       []byte `json:"ref"`
}

// 这一集是否已经绑定过这个弹幕源。只用于在拉取前省掉一次注定 409 的拉取，并发时以唯一约束为准。
func (q *Queries) BindingExists(ctx context.Context, arg BindingExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, bindingExists, arg.EpisodeID, arg.Adapter, arg.Ref)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const episodeExists = `-- name: EpisodeExists :one
SELECT EXISTS (SELECT 1 FROM episodes WHERE id = $1)
`

// 创建绑定前确认这一集存在，拉取之前就能返回 404。
func (q *Queries) EpisodeExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, episodeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertBinding = `-- name: InsertBinding :one
INSERT INTO bindings (episode_id, adapter, ref, title, duration)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertBindingParams struct {
	EpisodeID int64  `json:"episodeId"`
	Adapter   string `json:"adapter"`
	Ref       []byte `json:"ref"`
	Title     string `json:"title"`
	Duration  int32  `json:"duration"`
}

// 同一集重复绑定同一个弹幕源时撞上唯一约束 (episode_id, adapter, ref)。
func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBinding,
		arg.EpisodeID,
		arg.Adapter,
		arg.Ref,
		arg.Title,
		arg.Duration,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDanmaku = `-- name: InsertDanmaku :execrows
INSERT INTO danmaku (binding_id, source_id, time_ms, mode, color, text)
SELECT $1::bigint,
       unnest($2::bigint[]),
       unnest($3::int[]),
       unnest($4::smallint[]),
       unnest($5::int[]),
       unnest($6::text[])
ON CONFLICT DO NOTHING
`

type InsertDanmakuParams struct {
	BindingID int64    `json:"bindingId"`
	SourceIds []int64  `json:"sourceIds"`
	TimeMs    []int32  `json:"timeMs"`
	Modes     []int16  `json:"modes"`
	Colors    []int32  `json:"colors"`
	Texts     []string `json:"texts"`
}

// 写入一次拉取的弹幕，五个等长的数组按下标一一对应（SELECT 列表里的多个 unnest 同步展开）。
// 按主键 (binding_id, source_id) 去重：已有的、以及同一批里重复的原始 ID 都跳过，返回实际插入的条数。
func (q *Queries) InsertDanmaku(ctx context.Context, arg InsertDanmakuParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDanmaku,
		arg.BindingID,
		arg.SourceIds,
		arg.TimeMs,
		arg.Modes,
		arg.Colors,
		arg.Texts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBindingsBySeries = `-- name: ListBindingsBySeries :many
SELECT b.id, b.episode_id, b.adapter, b.ref, b."offset", b.scale, b.mode, b.status, b.content_version, b.danmaku_count, b.title, b.duration, b.last_fetched_at, b.created_at, b.updated_at
FROM bindings b
JOIN episodes e ON e.id = b.episode_id
JOIN seasons se ON se.id = e.season_id
WHERE se.series_id = $1
ORDER BY b.id
`

// 剧详情用：一部剧所有集的绑定，按创建顺序排列。
func (q *Queries) ListBindingsBySeries(ctx context.Context, seriesID int64) ([]Binding, error) {
	rows, err := q.db.Query(ctx, listBindingsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Binding{}
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.Adapter,
			&i.Ref,
			&i.Offset,
			&i.Scale,
			&i.Mode,
			&i.Status,
			&i.ContentVersion,
			&i.DanmakuCount,
			&i.Title,
			&i.Duration,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEpisode = `-- name: LockEpisode :one
SELECT id
FROM episodes
WHERE id = $1
FOR KEY SHARE
`

// 创建绑定的写入事务的第一句：锁住这一集到提交，期间删不掉它。FOR KEY SHARE 与同步的 upsert 兼容。
// 这一集已被删除时没有行。
func (q *Queries) LockEpisode(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockEpisode, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const recordFetch = `-- name: RecordFetch :one
UPDATE bindings
SET danmaku_count   = danmaku_count + $1::int,
    content_version = content_version + ($1::int > 0)::int,
    title           = $2,
    duration        = $3,
    status          = 'active',
    last_fetched_at = now(),
    updated_at      = now()
WHERE id = $4
RETURNING id, episode_id, adapter, ref, "offset", scale, mode, status, content_version, danmaku_count, title, duration, last_fetched_at, created_at, updated_at
`

type RecordFetchParams struct {
	Added    int32  `json:"added"`
	Title    string `json:"title"`
	Duration int32  `json:"duration"`
	ID       int64  `json:"id"`
}

// 一次拉取写入弹幕之后更新绑定：新增条数计入 danmaku_count，插入了新弹幕时 content_version 加 1；
// 标题、时长用这次拉取的值覆盖；拉取成功即为 active。只更新拉取相关的列，不覆盖 offset。
func (q *Queries) RecordFetch(ctx context.Context, arg RecordFetchParams) (Binding, error) {
	row := q.db.QueryRow(ctx, recordFetch,
		arg.Added,
		arg.Title,
		arg.Duration,
		arg.ID,
	)
	var i Binding
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Adapter,
		&i.Ref,
		&i.Offset,
		&i.Scale,
		&i.Mode,
		&i.Status,
		&i.ContentVersion,
		&i.DanmakuCount,
		&i.Title,
		&i.Duration,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
