// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package repository

import (
	"context"
)

const getSeries = `-- name: GetSeries :one
SELECT id, type, title, original_title, year, created_at, updated_at, poster_image_id
FROM series
WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.OriginalTitle,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosterImageID,
	)
	return i, err
}

const listEpisodesBySeries = `-- name: ListEpisodesBySeries :many
SELECT e.id, e.season_id, e.number, e.title, e.duration, e.created_at, e.updated_at
FROM episodes e
JOIN seasons se ON se.id = e.season_id
WHERE se.series_id = $1
ORDER BY e.number
`

// 一部剧的全部集，按集号排序。
func (q *Queries) ListEpisodesBySeries(ctx context.Context, seriesID int64) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Number,
			&i.Title,
			&i.Duration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonsBySeries = `-- name: ListSeasonsBySeries :many
SELECT id, number, title
FROM seasons
WHERE series_id = $1
ORDER BY number
`

type ListSeasonsBySeriesRow struct {
	ID     int64   `json:"id"`
	Number int32   `json:"number"`
	Title  *string `json:"title"`
}

// 只选剧详情用到的列，不取搜索列。
func (q *Queries) ListSeasonsBySeries(ctx context.Context, seriesID int64) ([]ListSeasonsBySeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeasonsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonsBySeriesRow{}
	for rows.Next() {
		var i ListSeasonsBySeriesRow
		if err := rows.Scan(&i.ID, &i.Number, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeries = `-- name: ListSeries :many
SELECT s.id, s.type, s.title, s.original_title, s.year, s.poster_image_id,
       count(DISTINCT se.id)::int AS season_count,
       count(e.id)::int           AS episode_count
FROM series s
LEFT JOIN seasons se ON se.series_id = s.id
LEFT JOIN episodes e ON e.season_id = se.id
GROUP BY s.id
ORDER BY s.id
`

type ListSeriesRow struct {
	ID            int64   `json:"id"`
	Type          string  `json:"type"`
	Title         string  `json:"title"`
	OriginalTitle *string `json:"originalTitle"`
	Year          *int32  `json:"year"`
	PosterImageID *int64  `json:"posterImageId"`
	SeasonCount   int32   `json:"seasonCount"`
	EpisodeCount  int32   `json:"episodeCount"`
}

// 剧列表：全部剧连同季数、集数，一条 SQL 聚合。没有季、集的剧计为 0。
func (q *Queries) ListSeries(ctx context.Context) ([]ListSeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesRow{}
	for rows.Next() {
		var i ListSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.OriginalTitle,
			&i.Year,
			&i.PosterImageID,
			&i.SeasonCount,
			&i.EpisodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeriesPoster = `-- name: SetSeriesPoster :exec
UPDATE series
SET poster_image_id = $2
WHERE id = $1
`

type SetSeriesPosterParams struct {
	ID            int64  `json:"id"`
	PosterImageID *int64 `json:"posterImageId"`
}

// 剧指向新的海报，没有图时为 null。
func (q *Queries) SetSeriesPoster(ctx context.Context, arg SetSeriesPosterParams) error {
	_, err := q.db.Exec(ctx, setSeriesPoster, arg.ID, arg.PosterImageID)
	return err
}

const upsertEpisode = `-- name: UpsertEpisode :one
INSERT INTO episodes (season_id, number, title, duration)
VALUES ($1, $2, $3, $4)
ON CONFLICT (season_id, number) DO UPDATE
SET title      = excluded.title,
    duration   = excluded.duration,
    updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertEpisodeParams struct {
	SeasonID int64   `json:"seasonId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
	Duration *int32  `json:"duration"`
}

type UpsertEpisodeRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (season_id, number) 写入一集，规则同 UpsertSeries。
func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (UpsertEpisodeRow, error) {
	row := q.db.QueryRow(ctx, upsertEpisode,
		arg.SeasonID,
		arg.Number,
		arg.Title,
		arg.Duration,
	)
	var i UpsertEpisodeRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertSeason = `-- name: UpsertSeason :one
INSERT INTO seasons (series_id, number, title)
VALUES ($1, $2, $3)
ON CONFLICT (series_id, number) DO UPDATE
SET title      = excluded.title,
    updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertSeasonParams struct {
	SeriesID int64   `json:"seriesId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
}

type UpsertSeasonRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (series_id, number) 写入一季，规则同 UpsertSeries。
func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (UpsertSeasonRow, error) {
	row := q.db.QueryRow(ctx, upsertSeason, arg.SeriesID, arg.Number, arg.Title)
	var i UpsertSeasonRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO series (type, title, original_title, year)
VALUES ($1, $2, $3, $4)
ON CONFLICT (type, title, year) DO UPDATE
SET original_title = excluded.original_title,
    updated_at     = now()
RETURNING id, (xmax = 0)::boolean AS created, poster_image_id
`

type UpsertSeriesParams struct {
	Type          string  `json:"type"`
	Title         string  `json:"title"`
	OriginalTitle *string `json:"originalTitle"`
	Year          *int32  `json:"year"`
}

type UpsertSeriesRow struct {
	ID            int64  `json:"id"`
	Created       bool   `json:"created"`
	PosterImageID *int64 `json:"posterImageId"`
}

// 按自然键 (type, title, year) 写入一部剧：匹配上就用目录源的数据覆盖键以外的字段，匹配不上就新增。
// created 表示这一行是这次新增的：新插入的行 xmax 为 0，ON CONFLICT DO UPDATE 更新过的行不为 0。
// 海报由同步核心随后按 sha256 处理，这里带回剧现在的海报。
func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (UpsertSeriesRow, error) {
	row := q.db.QueryRow(ctx, upsertSeries,
		arg.Type,
		arg.Title,
		arg.OriginalTitle,
		arg.Year,
	)
	var i UpsertSeriesRow
	err := row.Scan(&i.ID, &i.Created, &i.PosterImageID)
	return i, err
}
