// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package repository

import (
	"context"
)

const upsertEpisode = `-- name: UpsertEpisode :one
INSERT INTO episodes (season_id, number, title, duration)
VALUES ($1, $2, $3, $4)
ON CONFLICT (season_id, number) DO UPDATE
SET title      = excluded.title,
    duration   = excluded.duration,
    updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertEpisodeParams struct {
	SeasonID int64   `json:"seasonId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
	Duration *int32  `json:"duration"`
}

type UpsertEpisodeRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (season_id, number) 写入一集，规则同 UpsertSeries。
func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (UpsertEpisodeRow, error) {
	row := q.db.QueryRow(ctx, upsertEpisode,
		arg.SeasonID,
		arg.Number,
		arg.Title,
		arg.Duration,
	)
	var i UpsertEpisodeRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertSeason = `-- name: UpsertSeason :one
INSERT INTO seasons (series_id, number, title)
VALUES ($1, $2, $3)
ON CONFLICT (series_id, number) DO UPDATE
SET title      = excluded.title,
    updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertSeasonParams struct {
	SeriesID int64   `json:"seriesId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
}

type UpsertSeasonRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (series_id, number) 写入一季，规则同 UpsertSeries。
func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (UpsertSeasonRow, error) {
	row := q.db.QueryRow(ctx, upsertSeason, arg.SeriesID, arg.Number, arg.Title)
	var i UpsertSeasonRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO series (type, title, original_title, year)
VALUES ($1, $2, $3, $4)
ON CONFLICT (type, title, year) DO UPDATE
SET original_title = excluded.original_title,
    updated_at     = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertSeriesParams struct {
	Type          string  `json:"type"`
	Title         string  `json:"title"`
	OriginalTitle *string `json:"originalTitle"`
	Year          *int32  `json:"year"`
}

type UpsertSeriesRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// 按自然键 (type, title, year) 写入一部剧：匹配上就用目录源的数据覆盖键以外的字段，匹配不上就新增。
// created 表示这一行是这次新增的：新插入的行 xmax 为 0，ON CONFLICT DO UPDATE 更新过的行不为 0。
func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (UpsertSeriesRow, error) {
	row := q.db.QueryRow(ctx, upsertSeries,
		arg.Type,
		arg.Title,
		arg.OriginalTitle,
		arg.Year,
	)
	var i UpsertSeriesRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
