// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: danmaku.sql

package repository

import (
	"context"
)

const listBindingsByEpisode = `-- name: ListBindingsByEpisode :many
SELECT id, episode_id, adapter, ref, "offset", scale, status, content_version, danmaku_count, title, duration, last_fetched_at, created_at, updated_at
FROM bindings
WHERE episode_id = $1
ORDER BY id
`

// 读取一集的弹幕用：这一集的全部绑定（含失效的），按创建顺序排列。集不存在时没有行。
func (q *Queries) ListBindingsByEpisode(ctx context.Context, episodeID int64) ([]Binding, error) {
	rows, err := q.db.Query(ctx, listBindingsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Binding{}
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.Adapter,
			&i.Ref,
			&i.Offset,
			&i.Scale,
			&i.Status,
			&i.ContentVersion,
			&i.DanmakuCount,
			&i.Title,
			&i.Duration,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDanmakuByBinding = `-- name: ListDanmakuByBinding :many
SELECT source_id, time_ms, mode, color, text
FROM danmaku
WHERE binding_id = $1
`

type ListDanmakuByBindingRow struct {
	SourceID int64  `json:"sourceId"`
	TimeMs   int32  `json:"timeMs"`
	Mode     int16  `json:"mode"`
	Color    int32  `json:"color"`
	Text     string `json:"text"`
}

// 一个绑定落库的弹幕，时间未校正。合并时重新排序，这里不排。
// 一条 SELECT 读完：清空后重新拉取在一个事务里完成，读到的要么全旧、要么全新。
func (q *Queries) ListDanmakuByBinding(ctx context.Context, bindingID int64) ([]ListDanmakuByBindingRow, error) {
	rows, err := q.db.Query(ctx, listDanmakuByBinding, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDanmakuByBindingRow{}
	for rows.Next() {
		var i ListDanmakuByBindingRow
		if err := rows.Scan(
			&i.SourceID,
			&i.TimeMs,
			&i.Mode,
			&i.Color,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
