// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: danmaku.sql

package repository

import (
	"context"
)

const listBindingsByEpisode = `-- name: ListBindingsByEpisode :many
SELECT id, episode_id, adapter, ref, "offset", scale, status, content_version, danmaku_count, title, duration, last_fetched_at, created_at, updated_at, season_binding_id, kind, file_count, fetch_attempted_at
FROM bindings
WHERE episode_id = $1
ORDER BY id
`

// 读取一集的弹幕用：这一集的全部绑定（含失效的），按创建顺序排列。集不存在时没有行。
func (q *Queries) ListBindingsByEpisode(ctx context.Context, episodeID int64) ([]Binding, error) {
	rows, err := q.db.Query(ctx, listBindingsByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Binding{}
	for rows.Next() {
		var i Binding
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.Adapter,
			&i.Ref,
			&i.Offset,
			&i.Scale,
			&i.Status,
			&i.ContentVersion,
			&i.DanmakuCount,
			&i.Title,
			&i.Duration,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SeasonBindingID,
			&i.Kind,
			&i.FileCount,
			&i.FetchAttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDanmakuByBindings = `-- name: ListDanmakuByBindings :many
SELECT binding_id, source_id, time_ms, mode, color, text
FROM danmaku
WHERE binding_id = ANY($1::bigint[])
`

// 这些绑定落库的弹幕，时间未校正，带上所属的绑定。合并时重新排序，这里不排。
// 一条 SELECT 读完：清空后重新拉取在一个事务里完成，每个绑定读到的要么全旧、要么全新。
func (q *Queries) ListDanmakuByBindings(ctx context.Context, bindingIds []int64) ([]Danmaku, error) {
	rows, err := q.db.Query(ctx, listDanmakuByBindings, bindingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Danmaku{}
	for rows.Next() {
		var i Danmaku
		if err := rows.Scan(
			&i.BindingID,
			&i.SourceID,
			&i.TimeMs,
			&i.Mode,
			&i.Color,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
