// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"
)

type Binding struct {
	ID              int64      `json:"id"`
	EpisodeID       int64      `json:"episodeId"`
	Adapter         *string    `json:"adapter"`
	Ref             []byte     `json:"ref"`
	Offset          float64    `json:"offset"`
	Scale           float64    `json:"scale"`
	Status          string     `json:"status"`
	ContentVersion  int32      `json:"contentVersion"`
	DanmakuCount    int32      `json:"danmakuCount"`
	Title           string     `json:"title"`
	Duration        *int32     `json:"duration"`
	LastFetchedAt   *time.Time `json:"lastFetchedAt"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	SeasonBindingID *int64     `json:"seasonBindingId"`
	Kind            string     `json:"kind"`
	FileCount       int32      `json:"fileCount"`
}

type BindingFile struct {
	ID         int64     `json:"id"`
	BindingID  int64     `json:"bindingId"`
	Name       string    `json:"name"`
	Sha256     []byte    `json:"sha256"`
	Size       int32     `json:"size"`
	Content    []byte    `json:"content"`
	UploadedAt time.Time `json:"uploadedAt"`
}

type Danmaku struct {
	BindingID int64  `json:"bindingId"`
	SourceID  int64  `json:"sourceId"`
	TimeMs    int32  `json:"timeMs"`
	Mode      int16  `json:"mode"`
	Color     int32  `json:"color"`
	Text      string `json:"text"`
}

type Episode struct {
	ID        int64     `json:"id"`
	SeasonID  int64     `json:"seasonId"`
	Number    int32     `json:"number"`
	Title     *string   `json:"title"`
	Duration  *int32    `json:"duration"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Image struct {
	ID          int64     `json:"id"`
	ContentType string    `json:"contentType"`
	Data        []byte    `json:"data"`
	Sha256      []byte    `json:"sha256"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Lease struct {
	Key       string    `json:"key"`
	Token     int64     `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type Season struct {
	ID           int64     `json:"id"`
	SeriesID     int64     `json:"seriesId"`
	Number       int32     `json:"number"`
	Title        *string   `json:"title"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	SearchVector string    `json:"searchVector"`
}

type SeasonBinding struct {
	ID              int64      `json:"id"`
	SeasonID        int64      `json:"seasonId"`
	Adapter         string     `json:"adapter"`
	Ref             []byte     `json:"ref"`
	Title           string     `json:"title"`
	Finished        bool       `json:"finished"`
	MappingFrom     int32      `json:"mappingFrom"`
	MappingTo       int32      `json:"mappingTo"`
	Follow          bool       `json:"follow"`
	Status          string     `json:"status"`
	LastError       *string    `json:"lastError"`
	LastCheckedAt   *time.Time `json:"lastCheckedAt"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	EpisodePatterns []string   `json:"episodePatterns"`
	NumberedByRule  bool       `json:"numberedByRule"`
}

type SeasonBindingHandled struct {
	SeasonBindingID int64     `json:"seasonBindingId"`
	Ref             []byte    `json:"ref"`
	EpisodeID       int64     `json:"episodeId"`
	CreatedAt       time.Time `json:"createdAt"`
}

type SeasonBindingItem struct {
	SeasonBindingID int64      `json:"seasonBindingId"`
	Ref             []byte     `json:"ref"`
	Position        int32      `json:"position"`
	Number          *int32     `json:"number"`
	UnmatchedReason *string    `json:"unmatchedReason"`
	Label           string     `json:"label"`
	LastError       *string    `json:"lastError"`
	LastErrorAt     *time.Time `json:"lastErrorAt"`
}

type Series struct {
	ID            int64     `json:"id"`
	Type          string    `json:"type"`
	Title         string    `json:"title"`
	OriginalTitle *string   `json:"originalTitle"`
	Year          *int32    `json:"year"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	PosterImageID *int64    `json:"posterImageId"`
}

type SyncRun struct {
	ID              int64      `json:"id"`
	Trigger         string     `json:"trigger"`
	Status          string     `json:"status"`
	StartedAt       time.Time  `json:"startedAt"`
	FinishedAt      *time.Time `json:"finishedAt"`
	Total           *int32     `json:"total"`
	Done            int32      `json:"done"`
	CreatedSeries   int32      `json:"createdSeries"`
	CreatedSeasons  int32      `json:"createdSeasons"`
	CreatedEpisodes int32      `json:"createdEpisodes"`
	Warnings        []string   `json:"warnings"`
	WarningCount    int32      `json:"warningCount"`
	Error           *string    `json:"error"`
}
