// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateSyncRun(ctx context.Context, trigger string) (int64, error)
	// 只保留最近 keep 次：新同步开始时先删到剩 19 次，再插入这一次。
	DeleteOldSyncRuns(ctx context.Context, keep int32) error
	GetSyncRun(ctx context.Context, id int64) (SyncRun, error)
	// 把残留的 running（进程崩溃或被杀）改为 interrupted，结束时间未知，保持为空。
	// 只能在持有同步锁时调用：这时不会有正在进行的同步。
	InterruptRunningSyncRuns(ctx context.Context) (int64, error)
	// 列表不带警告正文。
	ListSyncRuns(ctx context.Context, limit int32) ([]ListSyncRunsRow, error)
	// 写入一次同步的进度或最终状态；状态不再是 running 时记下结束时间。
	UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) error
	// 按自然键 (season_id, number) 写入一集，规则同 UpsertSeries。
	UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (UpsertEpisodeRow, error)
	// 按自然键 (series_id, number) 写入一季，规则同 UpsertSeries。
	UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (UpsertSeasonRow, error)
	// 按自然键 (type, title, year) 写入一部剧：匹配上就用目录源的数据覆盖键以外的字段，匹配不上就新增。
	// created 表示这一行是这次新增的：新插入的行 xmax 为 0，ON CONFLICT DO UPDATE 更新过的行不为 0。
	UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (UpsertSeriesRow, error)
}

var _ Querier = (*Queries)(nil)
