// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package repository

import (
	"context"
)

const listEpisodesOfSeasons = `-- name: ListEpisodesOfSeasons :many
SELECT id, season_id, number, title
FROM episodes
WHERE season_id = ANY ($1::bigint[])
ORDER BY season_id, number
`

type ListEpisodesOfSeasonsRow struct {
	ID       int64   `json:"id"`
	SeasonID int64   `json:"seasonId"`
	Number   int32   `json:"number"`
	Title    *string `json:"title"`
}

// 搜索结果里各季的全部集，按季、集号排序。
func (q *Queries) ListEpisodesOfSeasons(ctx context.Context, seasonIds []int64) ([]ListEpisodesOfSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listEpisodesOfSeasons, seasonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodesOfSeasonsRow{}
	for rows.Next() {
		var i ListEpisodesOfSeasonsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Number,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSeasons = `-- name: SearchSeasons :many
SELECT se.id, se.number, s.type, s.title, s.year
FROM seasons se
JOIN series s ON s.id = se.series_id
WHERE se.search_vector @@ $1::text::tsquery
ORDER BY ts_rank('{0.1, 0.33, 0.67, 1.0}'::real[], se.search_vector, $1::text::tsquery) DESC,
         char_length(s.title),
         s.year DESC NULLS LAST,
         s.id,
         se.number = 0,
         se.number
LIMIT $2
`

type SearchSeasonsParams struct {
	Query   string `json:"query"`
	MaxRows int32  `json:"maxRows"`
}

type SearchSeasonsRow struct {
	ID     int64  `json:"id"`
	Number int32  `json:"number"`
	Type   string `json:"type"`
	Title  string `json:"title"`
	Year   *int32 `json:"year"`
}

// 目录搜索，query 是 Go 拼好的 tsquery 文本（fulltext.Query）。排序全在这里：
// ts_rank 降序（权重数组按 {D, C, B, A} 的顺序：A、B、C 为 1.0、0.67、0.33，D 不用）→ 剧名短的在前
// → 年份降序，无年份最后 → 剧 id → 季号，特别篇最后。调用方多取一条，用来判断后面还有没有。
func (q *Queries) SearchSeasons(ctx context.Context, arg SearchSeasonsParams) ([]SearchSeasonsRow, error) {
	rows, err := q.db.Query(ctx, searchSeasons, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSeasonsRow{}
	for rows.Next() {
		var i SearchSeasonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Type,
			&i.Title,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeasonSearchVector = `-- name: SetSeasonSearchVector :exec
UPDATE seasons
SET search_vector = $1::text::tsvector
WHERE id = $2
`

type SetSeasonSearchVectorParams struct {
	SearchVector string `json:"searchVector"`
	ID           int64  `json:"id"`
}

// 搜索列是 Go 生成的 tsvector 文本（catalog.SearchVector），直接转换，不经过 PostgreSQL 的分词器。
func (q *Queries) SetSeasonSearchVector(ctx context.Context, arg SetSeasonSearchVectorParams) error {
	_, err := q.db.Exec(ctx, setSeasonSearchVector, arg.SearchVector, arg.ID)
	return err
}
