// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season_bindings.sql

package repository

import (
	"context"
	"time"
)

const deleteBindingsBySeasonBinding = `-- name: DeleteBindingsBySeasonBinding :exec
DELETE FROM bindings
WHERE season_binding_id = $1::bigint
`

// 删除季绑定时"一起删"：它建出的绑定，弹幕随外键级联删除。
func (q *Queries) DeleteBindingsBySeasonBinding(ctx context.Context, seasonBindingID int64) error {
	_, err := q.db.Exec(ctx, deleteBindingsBySeasonBinding, seasonBindingID)
	return err
}

const deleteSeasonBinding = `-- name: DeleteSeasonBinding :exec
DELETE FROM season_bindings
WHERE id = $1
`

// 删除季绑定，条目与处理过的记录随外键级联删除，它建出的绑定的来源置空。
func (q *Queries) DeleteSeasonBinding(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSeasonBinding, id)
	return err
}

const deleteStaleSeasonBindingItems = `-- name: DeleteStaleSeasonBindingItems :exec
DELETE FROM season_binding_items i
WHERE i.season_binding_id = $1
  AND NOT EXISTS (SELECT 1 FROM unnest($2::text[]) AS r (ref) WHERE r.ref::jsonb = i.ref)
`

type DeleteStaleSeasonBindingItemsParams struct {
	SeasonBindingID int64    `json:"seasonBindingId"`
	Refs            []string `json:"refs"`
}

// 删掉合集里已经没有的条目。refs 是这次列出的全部 ref（JSON 文本），按 jsonb 比较。
func (q *Queries) DeleteStaleSeasonBindingItems(ctx context.Context, arg DeleteStaleSeasonBindingItemsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleSeasonBindingItems, arg.SeasonBindingID, arg.Refs)
	return err
}

const finishSeasonBindingCheck = `-- name: FinishSeasonBindingCheck :exec
UPDATE season_bindings
SET last_checked_at = $1::timestamptz,
    last_error      = $2,
    status          = CASE WHEN $3::boolean THEN 'dead' ELSE status END,
    updated_at      = now()
WHERE id = $4
`

type FinishSeasonBindingCheckParams struct {
	CheckedAt time.Time `json:"checkedAt"`
	Error     *string   `json:"error"`
	Dead      bool      `json:"dead"`
	ID        int64     `json:"id"`
}

// 一次检查结束（正常结束，或因错误、限流结束）：上次检查时间写为这一轮的开始时间，记下结束时的错误（没有时为 null）。
// dead 时标为失效（列出合集时合集已不存在）。
func (q *Queries) FinishSeasonBindingCheck(ctx context.Context, arg FinishSeasonBindingCheckParams) error {
	_, err := q.db.Exec(ctx, finishSeasonBindingCheck,
		arg.CheckedAt,
		arg.Error,
		arg.Dead,
		arg.ID,
	)
	return err
}

const getEpisodeIDByNumber = `-- name: GetEpisodeIDByNumber :one
SELECT id
FROM episodes
WHERE season_id = $1
  AND number = $2
`

type GetEpisodeIDByNumberParams struct {
	SeasonID int64 `json:"seasonId"`
	Number   int32 `json:"number"`
}

// 补建时按集号找本季的集。没有这一集时没有行。
func (q *Queries) GetEpisodeIDByNumber(ctx context.Context, arg GetEpisodeIDByNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, getEpisodeIDByNumber, arg.SeasonID, arg.Number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSeasonBinding = `-- name: GetSeasonBinding :one
SELECT id, season_id, adapter, ref, title, finished, mapping_from, mapping_to, follow, status, last_error, last_checked_at, created_at, updated_at, episode_patterns, numbered_by_rule
FROM season_bindings
WHERE id = $1
`

// 季绑定本身：补建读它，立即补建前确认它存在。不存在时没有行。
func (q *Queries) GetSeasonBinding(ctx context.Context, id int64) (SeasonBinding, error) {
	row := q.db.QueryRow(ctx, getSeasonBinding, id)
	var i SeasonBinding
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Adapter,
		&i.Ref,
		&i.Title,
		&i.Finished,
		&i.MappingFrom,
		&i.MappingTo,
		&i.Follow,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodePatterns,
		&i.NumberedByRule,
	)
	return i, err
}

const getSeasonBindingItemNumber = `-- name: GetSeasonBindingItemNumber :one
SELECT number
FROM season_binding_items
WHERE season_binding_id = $1
  AND ref = $2
`

type GetSeasonBindingItemNumberParams struct {
	SeasonBindingID int64  `json:"seasonBindingId"`
	Ref             []byte `json:"ref"`
}

// 补建处理一个条目之前重新读它的序号：补建进行中改了集号规则时用新认出的序号。条目已经不在时没有行，对不上时为 null。
func (q *Queries) GetSeasonBindingItemNumber(ctx context.Context, arg GetSeasonBindingItemNumberParams) (*int32, error) {
	row := q.db.QueryRow(ctx, getSeasonBindingItemNumber, arg.SeasonBindingID, arg.Ref)
	var number *int32
	err := row.Scan(&number)
	return number, err
}

const getSeasonBindingSummary = `-- name: GetSeasonBindingSummary :one
SELECT sb.id, sb.season_id, sb.adapter, sb.ref, sb.title, sb.finished, sb.mapping_from, sb.mapping_to, sb.follow, sb.status, sb.last_error, sb.last_checked_at, sb.created_at, sb.updated_at, sb.episode_patterns, sb.numbered_by_rule,
       (SELECT count(*) FROM bindings b WHERE b.season_binding_id = sb.id)::int AS binding_count,
       EXISTS (SELECT 1
               FROM leases l
               WHERE l.key = $1::text || sb.id
                 AND l.expires_at > now())::boolean AS running
FROM season_bindings sb
WHERE sb.id = $2
`

type GetSeasonBindingSummaryParams struct {
	LeasePrefix string `json:"leasePrefix"`
	ID          int64  `json:"id"`
}

type GetSeasonBindingSummaryRow struct {
	SeasonBinding SeasonBinding `json:"seasonBinding"`
	BindingCount  int32         `json:"bindingCount"`
	Running       bool          `json:"running"`
}

// 季绑定的 JSON：连同它建出的、现存的绑定数，以及是否正在补建（有没有没过期的、按季绑定的租约，见 database.LeaseSeasonBackfill，
// lease_prefix 为它的前缀）。不存在时没有行。
func (q *Queries) GetSeasonBindingSummary(ctx context.Context, arg GetSeasonBindingSummaryParams) (GetSeasonBindingSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSeasonBindingSummary, arg.LeasePrefix, arg.ID)
	var i GetSeasonBindingSummaryRow
	err := row.Scan(
		&i.SeasonBinding.ID,
		&i.SeasonBinding.SeasonID,
		&i.SeasonBinding.Adapter,
		&i.SeasonBinding.Ref,
		&i.SeasonBinding.Title,
		&i.SeasonBinding.Finished,
		&i.SeasonBinding.MappingFrom,
		&i.SeasonBinding.MappingTo,
		&i.SeasonBinding.Follow,
		&i.SeasonBinding.Status,
		&i.SeasonBinding.LastError,
		&i.SeasonBinding.LastCheckedAt,
		&i.SeasonBinding.CreatedAt,
		&i.SeasonBinding.UpdatedAt,
		&i.SeasonBinding.EpisodePatterns,
		&i.SeasonBinding.NumberedByRule,
		&i.BindingCount,
		&i.Running,
	)
	return i, err
}

const insertBackfilledBinding = `-- name: InsertBackfilledBinding :one
INSERT INTO bindings (episode_id, kind, adapter, ref, title, duration, season_binding_id, created_at)
VALUES ($1, 'link', $2::text, $3::jsonb, $4, $5::int, $6::bigint, $7)
ON CONFLICT (episode_id, adapter, ref) DO NOTHING
RETURNING id
`

type InsertBackfilledBindingParams struct {
	EpisodeID       int64     `json:"episodeId"`
	Adapter         string    `json:"adapter"`
	Ref             []byte    `json:"ref"`
	Title           string    `json:"title"`
	Duration        int32     `json:"duration"`
	SeasonBindingID int64     `json:"seasonBindingId"`
	CreatedAt       time.Time `json:"createdAt"`
}

// 补建出一个绑定，带上建出它的季绑定；建出时间由应用写入（追更按它算自动重新拉取的窗口）。
// 这一集已有同一个弹幕源的绑定时什么都不做，没有行。
func (q *Queries) InsertBackfilledBinding(ctx context.Context, arg InsertBackfilledBindingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBackfilledBinding,
		arg.EpisodeID,
		arg.Adapter,
		arg.Ref,
		arg.Title,
		arg.Duration,
		arg.SeasonBindingID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSeasonBinding = `-- name: InsertSeasonBinding :one
INSERT INTO season_bindings (season_id, adapter, ref, title, finished, mapping_from, mapping_to, episode_patterns, numbered_by_rule)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertSeasonBindingParams struct {
	SeasonID        int64    `json:"seasonId"`
	Adapter         string   `json:"adapter"`
	Ref             []byte   `json:"ref"`
	Title           string   `json:"title"`
	Finished        bool     `json:"finished"`
	MappingFrom     int32    `json:"mappingFrom"`
	MappingTo       int32    `json:"mappingTo"`
	EpisodePatterns []string `json:"episodePatterns"`
	NumberedByRule  bool     `json:"numberedByRule"`
}

// 同一季重复绑定同一个合集时撞上唯一约束 (season_id, adapter, ref)。
func (q *Queries) InsertSeasonBinding(ctx context.Context, arg InsertSeasonBindingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSeasonBinding,
		arg.SeasonID,
		arg.Adapter,
		arg.Ref,
		arg.Title,
		arg.Finished,
		arg.MappingFrom,
		arg.MappingTo,
		arg.EpisodePatterns,
		arg.NumberedByRule,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSeasonBindingHandled = `-- name: InsertSeasonBindingHandled :exec
INSERT INTO season_binding_handled (season_binding_id, ref, episode_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertSeasonBindingHandledParams struct {
	SeasonBindingID int64  `json:"seasonBindingId"`
	Ref             []byte `json:"ref"`
	EpisodeID       int64  `json:"episodeId"`
}

// 补建出一个绑定的同一个事务里记一条处理过的记录；已经记过时什么都不做。
func (q *Queries) InsertSeasonBindingHandled(ctx context.Context, arg InsertSeasonBindingHandledParams) error {
	_, err := q.db.Exec(ctx, insertSeasonBindingHandled, arg.SeasonBindingID, arg.Ref, arg.EpisodeID)
	return err
}

const listBoundSources = `-- name: ListBoundSources :many
SELECT e.number AS episode_number,
       b.ref,
       (b.season_binding_id IS NOT DISTINCT FROM sb.id)::boolean AS own
FROM season_bindings sb
JOIN episodes e ON e.season_id = sb.season_id
JOIN bindings b ON b.episode_id = e.id AND b.adapter = sb.adapter
WHERE sb.id = $1
`

type ListBoundSourcesRow struct {
	EpisodeNumber int32  `json:"episodeNumber"`
	Ref           []byte `json:"ref"`
	Own           bool   `json:"own"`
}

// 季绑定的季里、它的适配器现有的全部绑定：在哪一集、哪个弹幕源、是不是它建出的。
// 条目表据此分出已建绑定、集上已有（别人建的同一个弹幕源）和绑定已被删除。
func (q *Queries) ListBoundSources(ctx context.Context, id int64) ([]ListBoundSourcesRow, error) {
	rows, err := q.db.Query(ctx, listBoundSources, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoundSourcesRow{}
	for rows.Next() {
		var i ListBoundSourcesRow
		if err := rows.Scan(&i.EpisodeNumber, &i.Ref, &i.Own); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSeasonBindings = `-- name: ListDueSeasonBindings :many
SELECT id, never_checked, interval_due, new_episodes, refetch_due
FROM (SELECT sb.id,
             sb.last_checked_at,
             (sb.last_checked_at IS NULL)::boolean AS never_checked,
             COALESCE(sb.last_checked_at <= $1::timestamptz, false)::boolean AS interval_due,
             EXISTS (SELECT 1 FROM episodes e WHERE e.season_id = sb.season_id AND e.created_at > sb.last_checked_at) AS new_episodes,
             EXISTS (SELECT 1
                     FROM bindings b
                     WHERE b.season_binding_id = sb.id
                       AND b.created_at > $2::timestamptz
                       AND b.last_fetched_at <= $1::timestamptz
                       AND b.last_fetched_at > sb.last_checked_at - make_interval(secs => $3::float8)) AS refetch_due
      FROM season_bindings sb
      WHERE sb.follow
        AND ($4::bigint IS NULL OR sb.id = $4::bigint)) d
WHERE never_checked OR interval_due OR new_episodes OR refetch_due
ORDER BY last_checked_at NULLS FIRST, id
`

type ListDueSeasonBindingsParams struct {
	DueBefore            time.Time `json:"dueBefore"`
	CreatedAfter         time.Time `json:"createdAfter"`
	CheckIntervalSeconds float64   `json:"checkIntervalSeconds"`
	ID                   *int64    `json:"id"`
}

type ListDueSeasonBindingsRow struct {
	ID           int64 `json:"id"`
	NeverChecked bool  `json:"neverChecked"`
	IntervalDue  bool  `json:"intervalDue"`
	NewEpisodes  bool  `json:"newEpisodes"`
	RefetchDue   bool  `json:"refetchDue"`
}

// 追更的扫描：追更开着、并且满足以下任一条件的季绑定，按上次检查时间从早到晚，每个条件各是一列（到期的原因，记进日志）：
//
//	never_checked 从没检查过；interval_due 距上次检查已满一个检查周期（due_before = 现在 - 检查周期）；
//	new_episodes 这一季里有集的建出时间晚于上次检查时间；
//	refetch_due 它建出的、在重新拉取的窗口内（created_after = 现在 - 窗口）的绑定里，有距上次拉取已满一个检查周期（同样以 due_before 判断）、
//	而且是在上次检查开始之后才满的（满之前开始的那一轮已经试过拉取它，失败了等下一次定期的检查，不每次扫描都重试）。
//
// 检查周期（check_interval_seconds）与窗口由调用方按配置传入，时间规则只写在 service 里。
// id 不为空时只看这一个季绑定：扫描拿到它的租约之后再确认一次仍然到期。
func (q *Queries) ListDueSeasonBindings(ctx context.Context, arg ListDueSeasonBindingsParams) ([]ListDueSeasonBindingsRow, error) {
	rows, err := q.db.Query(ctx, listDueSeasonBindings,
		arg.DueBefore,
		arg.CreatedAfter,
		arg.CheckIntervalSeconds,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueSeasonBindingsRow{}
	for rows.Next() {
		var i ListDueSeasonBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.NeverChecked,
			&i.IntervalDue,
			&i.NewEpisodes,
			&i.RefetchDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeNumbersBySeason = `-- name: ListEpisodeNumbersBySeason :many
SELECT number
FROM episodes
WHERE season_id = $1
ORDER BY number
`

// 一季的全部集号：预览给出默认的集号对应，详情判断条目是否在等待对应的集。
func (q *Queries) ListEpisodeNumbersBySeason(ctx context.Context, seasonID int64) ([]int32, error) {
	rows, err := q.db.Query(ctx, listEpisodeNumbersBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentBackfilledBindings = `-- name: ListRecentBackfilledBindings :many
SELECT id, last_fetched_at
FROM bindings
WHERE season_binding_id = $1::bigint
  AND created_at > $2::timestamptz
ORDER BY last_fetched_at NULLS FIRST, id
`

type ListRecentBackfilledBindingsParams struct {
	SeasonBindingID int64     `json:"seasonBindingId"`
	CreatedAfter    time.Time `json:"createdAfter"`
}

type ListRecentBackfilledBindingsRow struct {
	ID            int64      `json:"id"`
	LastFetchedAt *time.Time `json:"lastFetchedAt"`
}

// 自动重新拉取的候选：季绑定建出的、建出时间晚于 created_after（现在 - 重新拉取的窗口）的绑定，按上次拉取时间从早到晚。
func (q *Queries) ListRecentBackfilledBindings(ctx context.Context, arg ListRecentBackfilledBindingsParams) ([]ListRecentBackfilledBindingsRow, error) {
	rows, err := q.db.Query(ctx, listRecentBackfilledBindings, arg.SeasonBindingID, arg.CreatedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentBackfilledBindingsRow{}
	for rows.Next() {
		var i ListRecentBackfilledBindingsRow
		if err := rows.Scan(&i.ID, &i.LastFetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonBindingHandled = `-- name: ListSeasonBindingHandled :many
SELECT h.ref,
       e.number AS episode_number
FROM season_binding_handled h
JOIN episodes e ON e.id = h.episode_id
WHERE h.season_binding_id = $1
`

type ListSeasonBindingHandledRow struct {
	Ref           []byte `json:"ref"`
	EpisodeNumber int32  `json:"episodeNumber"`
}

// 处理过的记录（季绑定建出过绑定的弹幕源），连同建在哪一集。
func (q *Queries) ListSeasonBindingHandled(ctx context.Context, seasonBindingID int64) ([]ListSeasonBindingHandledRow, error) {
	rows, err := q.db.Query(ctx, listSeasonBindingHandled, seasonBindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonBindingHandledRow{}
	for rows.Next() {
		var i ListSeasonBindingHandledRow
		if err := rows.Scan(&i.Ref, &i.EpisodeNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonBindingItems = `-- name: ListSeasonBindingItems :many
SELECT season_binding_id, ref, position, number, unmatched_reason, label, last_error, last_error_at
FROM season_binding_items
WHERE season_binding_id = $1
ORDER BY position
`

// 上次检查时的条目，按在合集里的顺序。
func (q *Queries) ListSeasonBindingItems(ctx context.Context, seasonBindingID int64) ([]SeasonBindingItem, error) {
	rows, err := q.db.Query(ctx, listSeasonBindingItems, seasonBindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeasonBindingItem{}
	for rows.Next() {
		var i SeasonBindingItem
		if err := rows.Scan(
			&i.SeasonBindingID,
			&i.Ref,
			&i.Position,
			&i.Number,
			&i.UnmatchedReason,
			&i.Label,
			&i.LastError,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonBindingSummariesBySeries = `-- name: ListSeasonBindingSummariesBySeries :many
SELECT sb.id, sb.season_id, sb.adapter, sb.ref, sb.title, sb.finished, sb.mapping_from, sb.mapping_to, sb.follow, sb.status, sb.last_error, sb.last_checked_at, sb.created_at, sb.updated_at, sb.episode_patterns, sb.numbered_by_rule,
       (SELECT count(*) FROM bindings b WHERE b.season_binding_id = sb.id)::int AS binding_count,
       EXISTS (SELECT 1
               FROM leases l
               WHERE l.key = $1::text || sb.id
                 AND l.expires_at > now())::boolean AS running
FROM season_bindings sb
JOIN seasons se ON se.id = sb.season_id
WHERE se.series_id = $2
ORDER BY sb.id
`

type ListSeasonBindingSummariesBySeriesParams struct {
	LeasePrefix string `json:"leasePrefix"`
	SeriesID    int64  `json:"seriesId"`
}

type ListSeasonBindingSummariesBySeriesRow struct {
	SeasonBinding SeasonBinding `json:"seasonBinding"`
	BindingCount  int32         `json:"bindingCount"`
	Running       bool          `json:"running"`
}

// 剧详情用：一部剧所有季的季绑定，列与 GetSeasonBindingSummary 相同，按创建顺序排列。
func (q *Queries) ListSeasonBindingSummariesBySeries(ctx context.Context, arg ListSeasonBindingSummariesBySeriesParams) ([]ListSeasonBindingSummariesBySeriesRow, error) {
	rows, err := q.db.Query(ctx, listSeasonBindingSummariesBySeries, arg.LeasePrefix, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonBindingSummariesBySeriesRow{}
	for rows.Next() {
		var i ListSeasonBindingSummariesBySeriesRow
		if err := rows.Scan(
			&i.SeasonBinding.ID,
			&i.SeasonBinding.SeasonID,
			&i.SeasonBinding.Adapter,
			&i.SeasonBinding.Ref,
			&i.SeasonBinding.Title,
			&i.SeasonBinding.Finished,
			&i.SeasonBinding.MappingFrom,
			&i.SeasonBinding.MappingTo,
			&i.SeasonBinding.Follow,
			&i.SeasonBinding.Status,
			&i.SeasonBinding.LastError,
			&i.SeasonBinding.LastCheckedAt,
			&i.SeasonBinding.CreatedAt,
			&i.SeasonBinding.UpdatedAt,
			&i.SeasonBinding.EpisodePatterns,
			&i.SeasonBinding.NumberedByRule,
			&i.BindingCount,
			&i.Running,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSeason = `-- name: LockSeason :one
SELECT id
FROM seasons
WHERE id = $1
FOR KEY SHARE
`

// 创建季绑定、补建的写入事务的第一句：锁住这一季到提交，期间删不掉它。这一季已被删除时没有行。
func (q *Queries) LockSeason(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockSeason, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const lockSeasonBindingForDelete = `-- name: LockSeasonBindingForDelete :one
SELECT id
FROM season_bindings
WHERE id = $1
FOR UPDATE
`

// 删除季绑定的事务的第一句：等进行中的补建写入事务提交，之后补建再也锁不到它。季绑定已被删除时没有行。
func (q *Queries) LockSeasonBindingForDelete(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockSeasonBindingForDelete, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const lockSeasonBindingShared = `-- name: LockSeasonBindingShared :one
SELECT id
FROM season_bindings
WHERE id = $1
FOR KEY SHARE
`

// 补建的写入事务的第二句（第一句锁季）：锁住季绑定到提交，期间删不掉它；之后的删除要等这个事务提交，再连同刚建出的绑定一起删掉。
// FOR KEY SHARE 与改集号对应、开关追更的 UPDATE 兼容。季绑定已被删除时没有行。
func (q *Queries) LockSeasonBindingShared(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockSeasonBindingShared, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const recordSeasonBindingListed = `-- name: RecordSeasonBindingListed :one
UPDATE season_bindings
SET status           = 'active',
    last_error       = NULL,
    title            = $2,
    finished         = $3,
    numbered_by_rule = $4,
    updated_at       = now()
WHERE id = $1
RETURNING episode_patterns
`

type RecordSeasonBindingListedParams struct {
	ID             int64  `json:"id"`
	Title          string `json:"title"`
	Finished       bool   `json:"finished"`
	NumberedByRule bool   `json:"numberedByRule"`
}

// 一次检查成功列出合集：季绑定恢复为正常、清掉错误，更新合集标题、完结标志与是否按集号规则编号。
// 返回集号规则：同一个事务里随后按它认出序号、写入条目；行锁让改集号规则的事务排在前面或后面，不会用旧规则覆盖新规则认出的序号。
// 季绑定已被删除时没有行。
func (q *Queries) RecordSeasonBindingListed(ctx context.Context, arg RecordSeasonBindingListedParams) ([]string, error) {
	row := q.db.QueryRow(ctx, recordSeasonBindingListed,
		arg.ID,
		arg.Title,
		arg.Finished,
		arg.NumberedByRule,
	)
	var episode_patterns []string
	err := row.Scan(&episode_patterns)
	return episode_patterns, err
}

const seasonBindingExists = `-- name: SeasonBindingExists :one
SELECT EXISTS (SELECT 1 FROM season_bindings WHERE season_id = $1 AND adapter = $2 AND ref = $3)
`

type SeasonBindingExistsParams struct {
	SeasonID int64  `json:"seasonId"`
	Adapter  string `json:"adapter"`
	Ref      []byte `json:"ref"`
}

// 这一季是否已经绑定过这个合集。只用于在列出合集前省掉一次注定 409 的请求，并发时以唯一约束为准。
func (q *Queries) SeasonBindingExists(ctx context.Context, arg SeasonBindingExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, seasonBindingExists, arg.SeasonID, arg.Adapter, arg.Ref)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const seasonExists = `-- name: SeasonExists :one
SELECT EXISTS (SELECT 1 FROM seasons WHERE id = $1)
`

// 预览、创建季绑定前确认这一季存在，列出合集之前就能返回 404。
func (q *Queries) SeasonExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, seasonExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSeasonBindingItemError = `-- name: SetSeasonBindingItemError :exec
UPDATE season_binding_items
SET last_error    = $1,
    last_error_at = $2
WHERE season_binding_id = $3
  AND ref = $4
`

type SetSeasonBindingItemErrorParams struct {
	Error           *string    `json:"error"`
	ErrorAt         *time.Time `json:"errorAt"`
	SeasonBindingID int64      `json:"seasonBindingId"`
	Ref             []byte     `json:"ref"`
}

// 条目补建失败：记下原因和时间，下次补建再试。error 为 null 时清掉（补建成功）。
func (q *Queries) SetSeasonBindingItemError(ctx context.Context, arg SetSeasonBindingItemErrorParams) error {
	_, err := q.db.Exec(ctx, setSeasonBindingItemError,
		arg.Error,
		arg.ErrorAt,
		arg.SeasonBindingID,
		arg.Ref,
	)
	return err
}

const updateSeasonBinding = `-- name: UpdateSeasonBinding :one
UPDATE season_bindings
SET follow           = coalesce($1, follow),
    mapping_from     = coalesce($2, mapping_from),
    mapping_to       = coalesce($3, mapping_to),
    episode_patterns = coalesce($4::text[], episode_patterns),
    updated_at       = now()
WHERE id = $5
RETURNING numbered_by_rule
`

type UpdateSeasonBindingParams struct {
	Follow          *bool    `json:"follow"`
	MappingFrom     *int32   `json:"mappingFrom"`
	MappingTo       *int32   `json:"mappingTo"`
	EpisodePatterns []string `json:"episodePatterns"`
	ID              int64    `json:"id"`
}

// 改集号对应、集号规则，开关追更：只改传了的字段。返回是否按集号规则编号：改了集号规则时，同一个事务里随后重新认出条目的序号。
// 不存在时没有行。
func (q *Queries) UpdateSeasonBinding(ctx context.Context, arg UpdateSeasonBindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, updateSeasonBinding,
		arg.Follow,
		arg.MappingFrom,
		arg.MappingTo,
		arg.EpisodePatterns,
		arg.ID,
	)
	var numbered_by_rule bool
	err := row.Scan(&numbered_by_rule)
	return numbered_by_rule, err
}

const upsertSeasonBindingItems = `-- name: UpsertSeasonBindingItems :exec
INSERT INTO season_binding_items (season_binding_id, ref, position, number, unmatched_reason, label)
SELECT $1::bigint,
       unnest($2::text[])::jsonb,
       unnest($3::int[]),
       nullif(unnest($4::int[]), -1),
       nullif(unnest($5::text[]), ''),
       unnest($6::text[])
ON CONFLICT (season_binding_id, ref) DO UPDATE
SET position         = excluded.position,
    number           = excluded.number,
    unmatched_reason = excluded.unmatched_reason,
    label            = excluded.label
`

type UpsertSeasonBindingItemsParams struct {
	SeasonBindingID int64    `json:"seasonBindingId"`
	Refs            []string `json:"refs"`
	Positions       []int32  `json:"positions"`
	Numbers         []int32  `json:"numbers"`
	Reasons         []string `json:"reasons"`
	Labels          []string `json:"labels"`
}

// 写入一次检查列出的条目（或改集号规则之后重新认出的序号），各数组按下标一一对应，ref 是 JSON 文本。
// 序号为 -1、原因为空串时存为 null。按 (季绑定, 弹幕源) upsert：已有的条目更新位置、序号与标签，上次失败的原因保留。
// 调用方保证 ref 不重复。同 InsertDanmaku，SELECT 列表里的多个 unnest 同步展开。
func (q *Queries) UpsertSeasonBindingItems(ctx context.Context, arg UpsertSeasonBindingItemsParams) error {
	_, err := q.db.Exec(ctx, upsertSeasonBindingItems,
		arg.SeasonBindingID,
		arg.Refs,
		arg.Positions,
		arg.Numbers,
		arg.Reasons,
		arg.Labels,
	)
	return err
}
