// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_runs.sql

package repository

import (
	"context"
	"time"
)

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (trigger, status, started_at)
VALUES ($1, 'running', $2)
RETURNING id
`

type CreateSyncRunParams struct {
	Trigger   string    `json:"trigger"`
	StartedAt time.Time `json:"startedAt"`
}

// 开始时间取自应用的时钟：定时同步按它算下一次的时间。
func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSyncRun, arg.Trigger, arg.StartedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteOldSyncRuns = `-- name: DeleteOldSyncRuns :exec
DELETE FROM sync_runs
WHERE id NOT IN (SELECT id FROM sync_runs ORDER BY id DESC LIMIT $1)
`

// 只保留最近 keep 次：新同步开始时先删到剩 19 次，再插入这一次。
func (q *Queries) DeleteOldSyncRuns(ctx context.Context, keep int32) error {
	_, err := q.db.Exec(ctx, deleteOldSyncRuns, keep)
	return err
}

const getSyncRun = `-- name: GetSyncRun :one
SELECT id, trigger, status, started_at, finished_at, total, done, created_series, created_seasons, created_episodes, warnings, warning_count, error
FROM sync_runs
WHERE id = $1
`

func (q *Queries) GetSyncRun(ctx context.Context, id int64) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getSyncRun, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Total,
		&i.Done,
		&i.CreatedSeries,
		&i.CreatedSeasons,
		&i.CreatedEpisodes,
		&i.Warnings,
		&i.WarningCount,
		&i.Error,
	)
	return i, err
}

const interruptRunningSyncRuns = `-- name: InterruptRunningSyncRuns :execrows
UPDATE sync_runs
SET status = 'interrupted'
WHERE status = 'running'
`

// 把残留的 running（进程崩溃或被杀）改为 interrupted，结束时间未知，保持为空。
// 只能在持有同步的租约时调用：这时不会有正在进行的同步。
func (q *Queries) InterruptRunningSyncRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, interruptRunningSyncRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSyncRuns = `-- name: ListSyncRuns :many
SELECT id, trigger, status, started_at, finished_at, total, done,
       created_series, created_seasons, created_episodes, warning_count, error
FROM sync_runs
ORDER BY id DESC
LIMIT $1
`

type ListSyncRunsRow struct {
	ID              int64      `json:"id"`
	Trigger         string     `json:"trigger"`
	Status          string     `json:"status"`
	StartedAt       time.Time  `json:"startedAt"`
	FinishedAt      *time.Time `json:"finishedAt"`
	Total           *int32     `json:"total"`
	Done            int32      `json:"done"`
	CreatedSeries   int32      `json:"createdSeries"`
	CreatedSeasons  int32      `json:"createdSeasons"`
	CreatedEpisodes int32      `json:"createdEpisodes"`
	WarningCount    int32      `json:"warningCount"`
	Error           *string    `json:"error"`
}

// 列表不带警告正文。
func (q *Queries) ListSyncRuns(ctx context.Context, limit int32) ([]ListSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, listSyncRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncRunsRow{}
	for rows.Next() {
		var i ListSyncRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Total,
			&i.Done,
			&i.CreatedSeries,
			&i.CreatedSeasons,
			&i.CreatedEpisodes,
			&i.WarningCount,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncRun = `-- name: UpdateSyncRun :exec
UPDATE sync_runs
SET status           = $1,
    total            = $2,
    done             = $3,
    created_series   = $4,
    created_seasons  = $5,
    created_episodes = $6,
    warnings         = $7,
    warning_count    = $8,
    error            = $9,
    finished_at      = CASE WHEN $1 = 'running' THEN NULL ELSE now() END
WHERE id = $10
`

type UpdateSyncRunParams struct {
	Status          string   `json:"status"`
	Total           *int32   `json:"total"`
	Done            int32    `json:"done"`
	CreatedSeries   int32    `json:"createdSeries"`
	CreatedSeasons  int32    `json:"createdSeasons"`
	CreatedEpisodes int32    `json:"createdEpisodes"`
	Warnings        []string `json:"warnings"`
	WarningCount    int32    `json:"warningCount"`
	Error           *string  `json:"error"`
	ID              int64    `json:"id"`
}

// 写入一次同步的进度或最终状态；状态不再是 running 时记下结束时间。
func (q *Queries) UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) error {
	_, err := q.db.Exec(ctx, updateSyncRun,
		arg.Status,
		arg.Total,
		arg.Done,
		arg.CreatedSeries,
		arg.CreatedSeasons,
		arg.CreatedEpisodes,
		arg.Warnings,
		arg.WarningCount,
		arg.Error,
		arg.ID,
	)
	return err
}
