// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package seasonbindingdb

import (
	"time"
)

type SeasonBinding struct {
	ID              int64      `json:"id"`
	SeasonID        int64      `json:"seasonId"`
	Adapter         string     `json:"adapter"`
	Ref             []byte     `json:"ref"`
	Title           string     `json:"title"`
	Finished        bool       `json:"finished"`
	MappingFrom     int32      `json:"mappingFrom"`
	MappingTo       int32      `json:"mappingTo"`
	Follow          bool       `json:"follow"`
	Status          string     `json:"status"`
	LastError       *string    `json:"lastError"`
	LastCheckedAt   *time.Time `json:"lastCheckedAt"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	EpisodePatterns []string   `json:"episodePatterns"`
	NumberedByRule  bool       `json:"numberedByRule"`
}

type SeasonBindingItem struct {
	SeasonBindingID int64      `json:"seasonBindingId"`
	Ref             []byte     `json:"ref"`
	Position        int32      `json:"position"`
	Number          *int32     `json:"number"`
	UnmatchedReason *string    `json:"unmatchedReason"`
	Label           string     `json:"label"`
	LastError       *string    `json:"lastError"`
	LastErrorAt     *time.Time `json:"lastErrorAt"`
}
